In [1]:
import numpy as np

In [2]:
range(10)

range(0, 10)

In [3]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
list(range(2,5))

[2, 3, 4]

In [5]:
list(range(2,7.5))

TypeError: 'float' object cannot be interpreted as an integer

In [6]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(0.5,10)

array([0.5, 1.5, 2.5, 3.5, 4.5, 5.5, 6.5, 7.5, 8.5, 9.5])

In [8]:
# arange() can generate floating pointn numbers as well

In [8]:
np.arange(1,10, 0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [11]:
np.arange(2,20, 1.5)

array([ 2. ,  3.5,  5. ,  6.5,  8. ,  9.5, 11. , 12.5, 14. , 15.5, 17. ,
       18.5])

In [12]:
np.arange(5,-4,-1)

array([ 5,  4,  3,  2,  1,  0, -1, -2, -3])

In [10]:
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [12]:
# divide 1 to 5 scale into 20 parts.

In [13]:
np.linspace(1,5,20, retstep = True)

(array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
        2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
        3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
        4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ]),
 0.21052631578947367)

In [14]:
# retstep will give jump size 

In [15]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])

In [14]:
np.logspace(1,50,10)

array([1.00000000e+01, 2.78255940e+06, 7.74263683e+11, 2.15443469e+17,
       5.99484250e+22, 1.66810054e+28, 4.64158883e+33, 1.29154967e+39,
       3.59381366e+44, 1.00000000e+50])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [19]:
np.zeros((3,2,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [20]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.ones((3,4,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [23]:
np.ones((3,4,2)) + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.],
        [6., 6.]]])

In [24]:
np.ones((3,4,2)) * 2

array([[[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]],

       [[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]]])

In [16]:
np.empty((2,3))

array([[4.63899412e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [17]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
# Identity matrix

In [22]:
np.empty((4,3))

array([[ 2. ,  3.5,  5. ],
       [ 6.5,  8. ,  9.5],
       [11. , 12.5, 14. ],
       [15.5, 17. , 18.5]])

In [23]:
d = np.eye(5)

In [24]:
d

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [25]:
d.shape

(5, 5)

In [26]:
d.size

25

In [27]:
d.ndim

2

In [29]:
a1  = np.random.randn(3,4)

In [30]:
a1

array([[ 3.03586331,  0.39615168, -0.01279583,  0.60290976],
       [ 0.60755494, -0.81719738,  0.02251894, -0.66485862],
       [-1.21391569, -1.16962606,  1.4126187 ,  0.14843689]])

In [31]:
import pandas as pd

In [32]:
pd.DataFrame(a1)

0         1         2         3
0  3.035863  0.396152 -0.012796  0.602910
1  0.607555 -0.817197  0.022519 -0.664859
2 -1.213916 -1.169626  1.412619  0.148437

In [33]:
a1

array([[ 3.03586331,  0.39615168, -0.01279583,  0.60290976],
       [ 0.60755494, -0.81719738,  0.02251894, -0.66485862],
       [-1.21391569, -1.16962606,  1.4126187 ,  0.14843689]])

In [34]:
# How to extract  -0.81719 from the array

In [35]:
a1[1][1]

-0.8171973751990139

In [40]:
a1[0:2, 0:2]

array([[ 3.03586331,  0.39615168],
       [ 0.60755494, -0.81719738]])

In [41]:
a1[1:3, 2:4]

array([[ 0.02251894, -0.66485862],
       [ 1.4126187 ,  0.14843689]])

In [42]:
#Upper bound is excluded


In [51]:
m1 = np.random.randint(1,3, (3,3))

In [52]:
m1

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [55]:
m2 = np.random.randint(2,4, (3,3))

In [56]:
m2

array([[2, 2, 2],
       [2, 3, 2],
       [2, 3, 2]])

In [57]:
m1 * m2
# This is not matrix multi[lication

array([[4, 4, 4],
       [2, 3, 2],
       [2, 6, 2]])

In [59]:
m1

array([[2, 2, 2],
       [1, 1, 1],
       [1, 2, 1]])

In [60]:
m2

array([[2, 2, 2],
       [2, 3, 2],
       [2, 3, 2]])

In [61]:
m1@m2
# This is matrix multopliaction

array([[12, 16, 12],
       [ 6,  8,  6],
       [ 8, 11,  8]])

In [62]:
# if m1 is mxn matrix and m2 is pxq matrix, then to multiply it
# n should be equal to p.

In [63]:
pow(m1,4)

array([[16, 16, 16],
       [ 1,  1,  1],
       [ 1, 16,  1]])

In [64]:
np.sqrt(m1)

array([[1.41421356, 1.41421356, 1.41421356],
       [1.        , 1.        , 1.        ],
       [1.        , 1.41421356, 1.        ]])

In [65]:
np.log10(m1)

array([[0.30103, 0.30103, 0.30103],
       [0.     , 0.     , 0.     ],
       [0.     , 0.30103, 0.     ]])

In [66]:
np.exp(m1)

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [2.71828183, 2.71828183, 2.71828183],
       [2.71828183, 7.3890561 , 2.71828183]])

In [67]:
m1 ** 2

array([[4, 4, 4],
       [1, 1, 1],
       [1, 4, 1]])

In [68]:
m1 + 5

array([[7, 7, 7],
       [6, 6, 6],
       [6, 7, 6]])