## NumPy

In [1]:
# NumPy :- Numerical Python.

In [1]:
import numpy as np

In [3]:
# Can perform almost every kind of mathematical operations using numpy

In [4]:
l = [1,2,3,4,4]

In [5]:
type(l)

list

In [6]:
np.array(l)

array([1, 2, 3, 4, 4])

In [7]:
a = np.array(l)

In [8]:
type(a)

numpy.ndarray

In [10]:
a1 = np.array([[1,2,3], [4,5,6]])

In [11]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
a2 = np.array([[[1,2,3], [4,5,6]]])

In [13]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [14]:
# To check their dimension, use ndim (n dimension).

In [15]:
a

array([1, 2, 3, 4, 4])

In [16]:
a1

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
a2

array([[[1, 2, 3],
        [4, 5, 6]]])

In [18]:
a.ndim

1

In [19]:
a1.ndim

2

In [20]:
a2.ndim

3

In [21]:
# one dimension- in one direction or on one axis only.
# two dimension- in two direction , ie on x and y axis.
# three dimension- in x, y and z axis.

In [26]:
a3 = np.array([[[1,2,3],[10,20,30]],[[4,5,6],[40,50,60]], [[7,8,9],[70,80,90]]])

In [27]:
a3

array([[[ 1,  2,  3],
        [10, 20, 30]],

       [[ 4,  5,  6],
        [40, 50, 60]],

       [[ 7,  8,  9],
        [70, 80, 90]]])

In [28]:
a3.ndim

3

In [29]:
l = [1,2,5,6,5,4,8]

In [34]:
np.asarray(l)

array([1, 2, 5, 6, 5, 4, 8])

In [33]:
np.array(l)

array([1, 2, 5, 6, 5, 4, 8])

In [32]:
np.asanyarray(l)

array([1, 2, 5, 6, 5, 4, 8])

In [35]:
np.matrix(l)

matrix([[1, 2, 5, 6, 5, 4, 8]])

### Deep copy and Shallow copy

    In the case of deep copy, a copy of the object is copied into another object. It means that any changes made to a copy of the object do not reflect in the original object. 

    In the case of shallow copy, a reference of an object is copied into another object. It means that any changes made to a copy of an object do reflect in the original object. In python, this is implemented using the “copy()” function. 



In [37]:
a = np.array(l)

In [38]:
a

array([1, 2, 5, 6, 5, 4, 8])

In [39]:
a1 = a

In [40]:
a1

array([1, 2, 5, 6, 5, 4, 8])

In [41]:
a

array([1, 2, 5, 6, 5, 4, 8])

In [43]:
a[0] = 100

In [44]:
a

array([100,   2,   5,   6,   5,   4,   8])

In [45]:
a1

array([100,   2,   5,   6,   5,   4,   8])

In [50]:
# Changes made in a is reflected in a1 as well.
# Same will be true for reverese as well ie changes made in a1 will be reflected in a as well

In [51]:
a

array([100,   2,   5,   6,   5,   4,   8])

In [48]:
a2 = np.copy(a)

In [49]:
a2

array([100,   2,   5,   6,   5,   4,   8])

In [56]:
a2[2] = 500

In [57]:
a2

array([100,   2, 500,   6,   5,   4,   8])

In [58]:
a

array([100,   2,   5,   6,   5,   4,   8])

In [59]:
# Changes made in a2 did not relected in a here.

In [61]:
a[6] = 80

In [62]:
a

array([100,   2,   5,   6,   5,   4,  80])

In [63]:
a2

array([100,   2, 500,   6,   5,   4,   8])

In [64]:
# Changes made in a did not relected in a2 as well.

In [3]:
np.fromfunction(lambda i,j: i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [4]:
np.random.rand(2,3)

array([[0.61003688, 0.19409718, 0.24065474],
       [0.38299939, 0.28263687, 0.96342447]])

In [5]:
np.random.rand(2,3)

array([[0.61612154, 0.95405699, 0.72466303],
       [0.49441011, 0.15127258, 0.47183284]])

In [6]:
np.random.rand(2,3,2)

array([[[0.45277455, 0.40904639],
        [0.72780631, 0.18242044],
        [0.9378798 , 0.5053864 ]],

       [[0.05249937, 0.61858149],
        [0.86260511, 0.6257295 ],
        [0.48041306, 0.56080461]]])

In [8]:
# 2 nos of 3x2 array generated above.

In [9]:
np.random.rand(2,3,3)

array([[[0.59017343, 0.78557061, 0.90178341],
        [0.91220622, 0.88898966, 0.91270941],
        [0.31070458, 0.44117524, 0.33319103]],

       [[0.36038449, 0.88587717, 0.1717874 ],
        [0.63936417, 0.92292563, 0.65365436],
        [0.69450736, 0.60428021, 0.33017024]]])

In [10]:
# 2 nos of 3x3 array generated above

In [12]:
d = np.random.rand(4,3)

In [13]:
d

array([[0.61615987, 0.28406738, 0.09066964],
       [0.18456165, 0.7162674 , 0.42310017],
       [0.00156924, 0.60330078, 0.74482298],
       [0.01225597, 0.66397091, 0.06325191]])

In [14]:
import pandas as pd

In [15]:
pd.DataFrame(d)

0         1         2
0  0.616160  0.284067  0.090670
1  0.184562  0.716267  0.423100
2  0.001569  0.603301  0.744823
3  0.012256  0.663971  0.063252

In [17]:
np.random.randint(0,5, (3,3))

array([[0, 2, 0],
       [0, 3, 1],
       [1, 0, 3]])

In [18]:
np.random.randint(0,10, (4,3))

array([[0, 0, 1],
       [4, 2, 5],
       [8, 5, 8],
       [3, 0, 4]])

In [19]:
# HEre low = 0, high =10 and array size 4x3

In [20]:
np.random.randint(0,10, (4,3,3))

array([[[5, 6, 2],
        [4, 8, 9],
        [7, 1, 3]],

       [[0, 3, 6],
        [4, 3, 1],
        [7, 3, 9]],

       [[8, 1, 5],
        [4, 1, 8],
        [4, 9, 9]],

       [[5, 3, 3],
        [2, 5, 2],
        [5, 5, 2]]])

In [22]:
np.random.randn(3,4,4)

array([[[-1.17401576, -0.41002389,  1.34152776, -0.72657308],
        [ 0.13918741, -0.30297145, -0.90615109, -0.57857421],
        [-0.59301941, -0.76994928, -0.73714526, -0.8613399 ],
        [ 0.77415019, -0.80770835,  1.38359665, -1.65014261]],

       [[ 0.43544945,  0.5778252 , -0.65638224, -1.24155342],
        [ 0.81983121,  0.3057364 , -0.5776768 , -0.25345982],
        [ 1.19070554, -1.18928881,  0.26835613,  1.46731134],
        [-0.4962543 ,  0.64323243,  0.55149815, -0.57533349]],

       [[ 0.5470692 , -2.60609443, -0.20041586,  0.61102171],
        [ 0.35091993, -1.72015778,  0.88647028,  1.3423883 ],
        [-1.28786606,  0.3468948 , -0.16544271,  0.42139217],
        [-1.36717068, -0.26446617, -1.23682789, -0.22875003]]])

In [23]:
np.random.randn(3,4)

array([[-0.78631557, -1.25730331, -0.31744277,  0.07507427],
       [ 0.81213342, -0.40590172, -0.03598752, -0.20789867],
       [ 0.95748782,  1.3373734 , -0.28081971, -0.16046592]])

In [25]:
# Here mean of data =0 and std deviation = 1 in random.randn

In [26]:
# To convert 3d data into 2d form, use reshape function

In [30]:
d = np.random.randint(0,10, (4,4,2))

In [31]:
d

array([[[4, 6],
        [3, 3],
        [2, 4],
        [3, 0]],

       [[6, 2],
        [0, 0],
        [7, 0],
        [5, 0]],

       [[4, 5],
        [4, 1],
        [9, 4],
        [2, 5]],

       [[8, 3],
        [1, 5],
        [7, 1],
        [0, 1]]])

In [29]:
pd.DataFrame(d)

ValueError: Must pass 2-d input. shape=(4, 4, 2)

In [34]:
d.reshape(2,16)

array([[4, 6, 3, 3, 2, 4, 3, 0, 6, 2, 0, 0, 7, 0, 5, 0],
       [4, 5, 4, 1, 9, 4, 2, 5, 8, 3, 1, 5, 7, 1, 0, 1]])

In [35]:
d.reshape(8,4)

array([[4, 6, 3, 3],
       [2, 4, 3, 0],
       [6, 2, 0, 0],
       [7, 0, 5, 0],
       [4, 5, 4, 1],
       [9, 4, 2, 5],
       [8, 3, 1, 5],
       [7, 1, 0, 1]])

In [36]:
d.reshape(1,32)

array([[4, 6, 3, 3, 2, 4, 3, 0, 6, 2, 0, 0, 7, 0, 5, 0, 4, 5, 4, 1, 9, 4,
        2, 5, 8, 3, 1, 5, 7, 1, 0, 1]])

In [37]:
d.reshape(16,-56)

array([[4, 6],
       [3, 3],
       [2, 4],
       [3, 0],
       [6, 2],
       [0, 0],
       [7, 0],
       [5, 0],
       [4, 5],
       [4, 1],
       [9, 4],
       [2, 5],
       [8, 3],
       [1, 5],
       [7, 1],
       [0, 1]])

In [38]:
d.reshape(32,-14456)

array([[4],
       [6],
       [3],
       [3],
       [2],
       [4],
       [3],
       [0],
       [6],
       [2],
       [0],
       [0],
       [7],
       [0],
       [5],
       [0],
       [4],
       [5],
       [4],
       [1],
       [9],
       [4],
       [2],
       [5],
       [8],
       [3],
       [1],
       [5],
       [7],
       [1],
       [0],
       [1]])

In [39]:
d.reshape(8,-6554)

array([[4, 6, 3, 3],
       [2, 4, 3, 0],
       [6, 2, 0, 0],
       [7, 0, 5, 0],
       [4, 5, 4, 1],
       [9, 4, 2, 5],
       [8, 3, 1, 5],
       [7, 1, 0, 1]])

In [40]:
d.reshape(4,5)

ValueError: cannot reshape array of size 32 into shape (4,5)

In [41]:
pd.DataFrame(d.reshape(8,-6554))

0  1  2  3
0  4  6  3  3
1  2  4  3  0
2  6  2  0  0
3  7  0  5  0
4  4  5  4  1
5  9  4  2  5
6  8  3  1  5
7  7  1  0  1

In [43]:
# Once we have array in 2d, we can use dataframe